pre-commit:
  commands:
    block-main:
      run: |
        branch=$(git rev-parse --abbrev-ref HEAD)
        if [ "$branch" = "main" ]; then
          echo "❌ Cannot commit directly to the main"
          exit 1
        fi

